apiVersion: integration/v1
kind: Integration
name: template
channel: stable
version: v20200514
summary: Keptn
license: Apache-2.0
homepage: https://github.com/relay-integrations/template
source: https://github.com/relay-integrations/template

description: |
  Keptn is a control-plane for DevOps automation of cloud-native applications.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
  - kubernetes
